# File pytest-test-steps.yml
#
# template for running pytest
#
# Copyright (c) 2019, Microsoft Corporation
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
parameters:
  root_package_folder: ''
  codecov_enabled: false # by default, we don't upload code coverage

steps:
- script: coverage run -m pytest
  displayName: 'Run UnitTests'
